name: Current date output

on:
  push:

jobs:
  print_date:
    runs-on: ubuntu-latest

    steps:
      - name: Get the current date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: print date
        run: |
          current_date=${{ steps.get-date.outputs.date }}
          echo "Поточна дата: $current_date"
