name: Current date output

on:
  push:

jobs:
  print_date:
    runs-on: ubuntu-latest

    steps:
      - name: Get the current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Print date
        run: |
          echo "Поточна дата: $CURRENT_DATE"
